name: "Fortify SAST"

on: 
  workflow_dispatch:

jobs:
  build:
    if: false
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Build using maven
        run: mvn clean install

  fortify-SAST:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Source Code
        uses: actions/checkout@v4
      - name: Fortify SAST Assessment
        uses: fortify/github-action@v1
        with:
          sast-scan: true
        env:
          SSC_URL: ${{secrets.SSC_URL}}
          SSC_TOKEN: ${{secrets.SSC_TOKEN}}
          SC_SAST_TOKEN: ${{secrets.CLIENT_AUTH_TOKEN}}
          # SSC_APPVERSION:<app-name>:<version-name>
          SC_SAST_SENSOR_VERSION: 24.4.0
          PACKAGE_EXTRA_OPTS:  -bt mvn
          DO_WAIT: true
          DO_EXPORT: true

    needs: build